### ISSUE TITLE
Yet another project, a minimalist distraction-free browser

### ISSUE THREAD

**Issue by felipealfonsog** [felipealfonsog/NovaNav#42]
hey! again a new different project here @PardesiCat it's a project inspired in a minimalist way to browse, distraction-free. try it out! There're a lot of things to do, but it's a work in progress! and it's working!...

**Comment by PardesiCat** [comment]
Namaste ,  yess good work again  its working  fine
the python version

![novanav](https://github.com/felipealfonsog/NovaNav/assets/55957190/a1286b12-f984-4d64-a826-684a39532589)

**Comment by felipealfonsog** [comment]
Install the C++ version ... it's much better ... and I'm improving the code in C++ a lot ... I'm thinking that maybe I will discontinue the Python version... I don't know yet ... But the C++ version is much better... try it out! on AUR it's known as 'novanav-cpp' .. let me know what you think ...  but in order to use the C++ version ... uninstall the Python version ... ỳay -R novanav' and install 'yay -S novanav-cpp`... :)

**Comment by PardesiCat** [comment]
Hei  i already say c version and tested here c version ss ... its also working great for me 

![novanav-cpp](https://github.com/felipealfonsog/NovaNav/assets/55957190/532ebf63-d009-4aba-ad94-6d828462d609)


I gave the Python feedback in the first place because I can understand some Python codes (because I was trying to learn Python).

**Comment by felipealfonsog** [comment]
> Hei i already say c version and tested here c version ss ... its also working great for me
> 
> ![novanav-cpp](https://private-user-images.githubusercontent.com/55957190/313610088-532ebf63-d009-4aba-ad94-6d828462d609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTM1NjAsIm5iZiI6MTcxMDc1MzI2MCwicGF0aCI6Ii81NTk1NzE5MC8zMTM2MTAwODgtNTMyZWJmNjMtZDAwOS00YWJhLWFkOTQtNmQ4Mjg0NjJkNjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA5MTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMTk3NTlhMDYwNWIyNDdhNTFmNzY4MGU5M2NiZWU5NDE0Y2VkZjhkNjlhYzM4OWEyYzU1NWQ5N2I5NDgxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d-rNJd-L_INapmd2W-vr7iTesNmuaqeEVjuu-HmYgjk)
> 
> I gave the Python feedback in the first place because I can understand some Python codes (because I was trying to learn Python).

Great ... it's actually C++ .. not C .. I'm improving a lot the code now actually... soon will be much better the C++ version ....

**Comment by PardesiCat** [comment]
oke got it ... when new version will release i will test it and give feedback

**Comment by felipealfonsog** [comment]
> Hei i already say c version and tested here c version ss ... its also working great for me
> 
> ![novanav-cpp](https://private-user-images.githubusercontent.com/55957190/313610088-532ebf63-d009-4aba-ad94-6d828462d609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTY1NDIsIm5iZiI6MTcxMDc1NjI0MiwicGF0aCI6Ii81NTk1NzE5MC8zMTM2MTAwODgtNTMyZWJmNjMtZDAwOS00YWJhLWFkOTQtNmQ4Mjg0NjJkNjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEwMDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZjU2NDNhYjYyNmU1NTFiOTk5MzE3MDA4N2Y5NjEzNmQwZGZlN2E1M2MyNDI4M2UxYmNhZjY5ZWIwNWU1ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7BeW1Bxb0iK9E93uQw0re6YdeeVfcm92Eh28hvasgmw)
> 
> I gave the Python feedback in the first place because I can understand some Python codes (because I was trying to learn Python).

if that's so, maybe you can help me to improve the Python version while I'm improving the code in the C++ version ... what do you think? ...  if that's so, clone the development branch and the code is in: src/python/novanav_linux.py

**Comment by PardesiCat** [comment]
yess i can help as much i can.... but am totally newbie in python, idk how much i can help..
but I can try.

**Comment by felipealfonsog** [comment]
> yess i can help as much i can.... but am totally newbie in python, idk how much i can help..
> 
> but I can try.

Yeah .. no matter if it's just one line of code or two hundred.. it's always great to share ! Keep it up! 🆙 I'm working a lot in the C++ version ... it has to be much better .. 🚀

**Comment by felipealfonsog** [comment]
Hi man, @PardesiCat I created the repo on Aur of arch Linux for the Python version - so I was thinking that maybe you wanna be part of it as a co-maintainer, what do you think?

**Comment by PardesiCat** [comment]
Sure. i can help as much i able to help.

**Comment by felipealfonsog** [comment]
> Sure. i can help as much i able to help. 

Do you have an account in AUR?

**Comment by PardesiCat** [comment]
NO But i made a aur account  

my user name is  **[Pardesi_Cat](https://aur.archlinux.org/account/Pardesi_Cat)**
mail :  **contact@pardesicat.xyz**

**Comment by felipealfonsog** [comment]
> NO But i made a aur account
> 
> my user name is **[Pardesi_Cat](https://aur.archlinux.org/account/Pardesi_Cat)** mail : **[contact@pardesicat.xyz](mailto:contact@pardesicat.xyz)**

Done. You're in!.
